### ISSUE TITLE
ARP Jobfair

### ISSUE THREAD

**Issue by Sidewinder92** [DouglasSherk/Apollo-RP#1]
Hello Douglas,

sorry to bother you. I am currently trying to figure out how to configure the jobfair.ini. for our TSRP server. Could you please explain what I have to enter exactly?

Thank you in advance,
Sidewinder92

**Comment by DouglasSherk** [comment]
The `jobfair.ini` file should either have a list of job IDs separated by line breaks, or it should contain a single character indicating the job access flag to add.

Suppose "Doctor" and "Nurse" both have job access flag `m`. Then putting the letter `m` in `jobfair.ini` will make both of those jobs available.

**Comment by Gregoru3746** [comment]
Sweet, got it working! Thanks!
