### ISSUE TITLE
ARP Jailmod

### ISSUE THREAD

**Issue by Sidewinder92** [DouglasSherk/Apollo-RP#2]
Hello Douglas,

sorry to bother you again. There is an issue regarding the ARP_Jailmod.amxx plugin. The jailmod locations have been set up as follows:

;carolincity_b2.ini
[Jail One]
origin "2548 -2435 124"
command "1"

[Jail Two]
origin "2560 -2308 124"
command "2"

[Jail Three]
origin "2563 -2186 124"
command "3"

The issue we are currently facing is the menu that does nothing whenever we attempt to send an unruly player to jail. 

L 12/03/2018 - 09:24:28: Invalid trie handle provided (600)
L 12/03/2018 - 09:24:28: [AMXX] Run time error 10 (plugin "ARP_JailMod.amxx") (native "TrieKeyExists") - debug not enabled!
L 12/03/2018 - 09:24:28: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).

Can you please help and give us an explanation on how to use it correctly?

Thank you so much in advance,
Sidewinder92

**Comment by Gregoru3746** [comment]
The jailmod.amxx has been disabled so only ARP_JailMod.amxx is running. The jailmodmenu comes up but when you select a jail cell nothing happens.

PutInJail(id,Index,Count - 1)
entity_set_origin(Index,g_JailOrigins[Num])
L 12/04/2018 - 11:22:14: [AMXX]    [0] ARP_JailMod.sma::PutInJail (line 598)
L 12/04/2018 - 11:22:14: [AMXX]    [1] ARP_JailMod.sma::JailCommand (line 447)
L 12/04/2018 - 11:25:01: [AMXX] Run time error 4: index out of bounds

**Comment by DouglasSherk** [comment]
Sorry, I'm swamped right now, and I remember seeing this issue before, but not the fix. I'll look into it this weekend.

**Comment by Gregoru3746** [comment]
No worries! Your help is much appreciated

**Comment by mallic** [comment]
@DouglasSherk Was there ever a solution to this issue? I am having the same problem.

**Comment by DouglasSherk** [comment]
> @DouglasSherk Was there ever a solution to this issue? I am having the same problem.

Don Punch has a copy of the ARP package where this problem is fixed. I'll check with him and get back to you.

**Comment by Gregoru3746** [comment]
I never did get this working, I'd still be interested in the fix!

**Comment by DouglasSherk** [comment]
Don sent me the full working ARP package, but I need to sit down and diff it against what I have up here on GitHub. Expect the update sometime this weekend or let me know if this is blocking you (@mallic, @Gregoru3746) and I might be able to get it to you faster.

**Comment by mallic** [comment]
That works for me, thanks for your effort on this. I appreciate it greatly. 

Also, I know this is unrelated to the original post, but does his copy fix zones? In the current github version, there is no explanation on how to use zones and trying to put one in, makes every single door entity just say the title of whatever is in zone 1.

**Comment by mallic** [comment]
Not pushing, just checking in @DouglasSherk

**Comment by DouglasSherk** [comment]
I rolled back `ARP_JailMod.sma` and `ARP_JailMod.amxx` to older versions that allegedly worked well, but I didn't test them. Please try them out and tell me how it goes.

**Comment by mallic** [comment]
So the arp_jailmod version you uploaded is jailmod++, which was written by MistaGee. Does it still work with the ARP flag system (IE cops automatically get it with flag A)

**Comment by mallic** [comment]
The SMA is correct, but when I installed the new .amxx, it was Jailmod++ by mistagee. Compiling the SMA was your jailmod. Everything works, except that when you are killed, you spawn outside the jail, but still have the jailed restrictions. Freeing players does work. This is an improvement that previous errors. 

Also, did you have any comment on the zones thing?

**Comment by Gregoru3746** [comment]
Hmmmm I installed this new(old) ARP_JailMod and mine threw this and doesn't teleport them to jail

[AMXX] Failed to open dictionary file: ts\addons\amxmodx\data\lang\jailmod.txt
L 05/05/2020 - 03:17:58: Invalid event (name "SendAudio") (plugin "ARP_JailMod.amxx")
L 05/05/2020 - 03:17:58: [AMXX] Displaying debug trace (plugin "ARP_JailMod.amxx")
L 05/05/2020 - 03:17:58: [AMXX] Run time error 10: native error (native "register_event")
L 05/05/2020 - 03:17:58: [AMXX]    [0] 3607.attach::plugin_init (line 223)

**Comment by DouglasSherk** [comment]
I grabbed the wrong version. Could you try this one and let me know how it goes?
https://www.dropbox.com/sh/ydi7eiu6gdggnxq/AABA5vUxJEo6KyqRJFQaKpoJa?preview=ARP_JailMod.amxx

**Comment by DouglasSherk** [comment]
> The SMA is correct, but when I installed the new .amxx, it was Jailmod++ by mistagee. Compiling the SMA was your jailmod.

Thanks, I uploaded the correct `ARP_JailMod.amxx` file.

> Everything works, except that when you are killed, you spawn outside the jail, but still have the jailed restrictions. Freeing players does work. This is an improvement that previous errors.

Unfortunately, I think that's a limitation of the old version. I'll double-check with Don and Vincetti to see if either of them have a fix.

> Also, did you have any comment on the zones thing?

I was hoping this version would just fix that problem, but I'll check with Vincetti. He and I did some tuning on zones a few days ago and maybe he got it working.

> Hmmmm I installed this new(old) ARP_JailMod and mine threw this and doesn't teleport them to jail
> 
> [AMXX] Failed to open dictionary file: ts\addons\amxmodx\data\lang\jailmod.txt
> L 05/05/2020 - 03:17:58: Invalid event (name "SendAudio") (plugin "ARP_JailMod.amxx")
> L 05/05/2020 - 03:17:58: [AMXX] Displaying debug trace (plugin "ARP_JailMod.amxx")
> L 05/05/2020 - 03:17:58: [AMXX] Run time error 10: native error (native "register_event")
> L 05/05/2020 - 03:17:58: [AMXX] [0] 3607.attach::plugin_init (line 223)

Sorry about that, please download the `ARP_JailMod.amxx` file again to deal with the problem described in https://github.com/DouglasSherk/Apollo-RP/issues/2#issuecomment-623945548

**Comment by Gregoru3746** [comment]
Im really not sure whats happening to the server. It doesnt seem to recognize any ARP_JailMod plugin exists. Like in game if you type arp_plugins in the console it doesnt show up, nor does anything show up about it in the console. So odd

**Comment by DouglasSherk** [comment]
> Im really not sure whats happening to the server. It doesnt seem to recognize any ARP_JailMod plugin exists. Like in game if you type arp_plugins in the console it doesnt show up, nor does anything show up about it in the console. So odd

Were you able to resolve this problem?

@mallic Could you share your compiled `ARP_JailMod.amxx` file? I don't have an easy way to compile plugins anymore.

**Comment by mallic** [comment]
http://kbargaming.com/files/ARP_JailMod.amxx

There ya go. You've got uploads disabled for anyone but you, so I can't upload it.

**Comment by Gregoru3746** [comment]
> > Im really not sure whats happening to the server. It doesnt seem to recognize any ARP_JailMod plugin exists. Like in game if you type arp_plugins in the console it doesnt show up, nor does anything show up about it in the console. So odd
> 
> Were you able to resolve this problem?
> 

Nope, no luck over here. There seems to be a big difference in size between the ARP_JailMod.amxx that I have vs what I downloaded from you guys. Mine is like 25kb and the one i downloaded from mallic is like 12kb. Would it be possible to get you guys to upload everything relate to JailMod (.amxx, .sma, etc) and I'll see if that helps?

Thanks again!

**Comment by mallic** [comment]
Do me a favor and show me the contents of your plugins.ini and plugins-arp.ini. I know for a fact what I uploaded works with the base ARP and the most recent version of AMXX with the TS compatibility plugin that is on the AMXX downloads page.

**Comment by Gregoru3746** [comment]
plugins-arp.ini:

https://pastebin.com/hB7sS2qf

plugins.ini:

https://pastebin.com/cgv49FVx

**Comment by mallic** [comment]
Looks like you don't have the TS addon for AMX. I recall vaguely that for some functions to work, you need the tsfun module, which is in that addon pack. (warning, if you add that pack, it overwrites some files, so you might have to merge what you selected in some config files into the ones you are dropping in.

**Comment by Gregoru3746** [comment]
Ahh yes its all coming back to me. Now the AMXMODX installer is doing that stupid thing where it refuses to install saying it cant see the files

**Comment by Gregoru3746** [comment]
tsfun_amxx.dll is in the amxmodx\modules folder and is enabled in the amxmodx\configs\modules.ini

https://pastebin.com/zApRKQJj

**Comment by Gregoru3746** [comment]
Wait...I dont know what I did but now its working...Neat!

**Comment by DouglasSherk** [comment]
Thanks for your help, @mallic!

@Gregoru3746 For clarity, which `ARP_JailMod.amxx` file are you currently using? I'd like to make sure I roll that one into master.

**Comment by Gregoru3746** [comment]
> @Gregoru3746 For clarity, which `ARP_JailMod.amxx` file are you currently using? I'd like to make sure I roll that one into master.

I am using this one from @mallic: http://kbargaming.com/files/ARP_JailMod.amxx

Thank you all for your help!

**Comment by DouglasSherk** [comment]
> I am using this one from @mallic: http://kbargaming.com/files/ARP_JailMod.amxx
> 
> Thank you all for your help!

Great, thanks! I replaced the `ARP_JailMod.amxx` file on master with this one.

**Comment by DouglasSherk** [comment]
> Also, I know this is unrelated to the original post, but does his copy fix zones? In the current github version, there is no explanation on how to use zones and trying to put one in, makes every single door entity just say the title of whatever is in zone 1.

Could you file another issue for this problem please?
